# Generated by Django 4.2.17 on 2024-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Логин покупателя')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Балансе')),
                ('age', models.IntegerField(verbose_name='Возраст покупателя')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Размер файлов игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limited', models.BooleanField(default=False, verbose_name='Ограничение 18+')),
                ('buyer', models.ManyToManyField(related_name='buyers', to='task1.buyer', verbose_name='Покупатели')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
